name: CyberKernel CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [xiaomi_kernel_sm8250_repo_push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: 环境配置
      run: |
        cd /home/runner/
        git clone https://github.com/localhosts-A/kernel_xiaomi_sm8250.git -b Simple_LMK --depth=1 Kernel
        mkdir /home/runner/Clang && cd /home/runner/Clang
        wget https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20240806-release/Clang-20.0.0git-20240806.tar.gz
        tar -xzvf Clang-20.0.0git-20240806.tar.gz && cd /home/runner/Kernel
        wget https://raw.githubusercontent.com/localhosts-A/CyberKernel_CI/master/CI.sh

    - name: 编译内核
      run: |
        cd /home/runner/Kernel
        sh CI.sh
