name: CyberKernel CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [xiaomi_kernel_sm8250_repo_push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: 环境配置
      run: |
        cd
        git clone https://github.com/localhosts-A/kernel_xiaomi_sm8250.git --depth=1 Kernel
        mkdir Clang && cd Clang
        wget https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20240806-release/Clang-20.0.0git-20240806.tar.gz
        tar -xzvf Clang-20.0.0git-20240806.tar.gz && cd
        cd Kernel && wget https://github.com/localhosts-A/CyberKernel_CI/raw/master/CI.sh

    - name: 编译内核
      run: |
        bash CI.sh
